-- Field Book — platform activity feed
--
-- Backs the Admin Dashboard's "Platform Activity" panel
-- (src/app/admin/dashboard.tsx). That panel previously rendered a
-- hardcoded ADMIN_ACTIVITY array — this table is the real-data
-- replacement, following the same "seed realistic rows, then let real
-- app actions append more over time" approach as the approvals/events
-- demo data seeded alongside this migration.
--
-- Deliberately generic (category + text + accent_color), not a foreign
-- key-heavy event-sourcing table: entries describe *something that
-- happened* (a cert issued, an organizer approved, a new registration,
-- etc.) for display purposes only. Nothing reads this table to drive
-- business logic — unlike `approvals`, which is the actual approval
-- workflow's source of truth. That keeps this table simple enough to
-- both seed convincingly up front and append to from real actions
-- (see approveEventApproval()/rejectEventApproval() in
-- src/lib/approvals.ts, which now also insert a row here).

create table public.platform_activity (
  id            uuid primary key default gen_random_uuid(),
  -- Matches the categories called out in the product brief: certificates
  -- issued, organizer approved, new student registrations, certificate
  -- template updated, new event submitted, event approved, event
  -- rejected, upcoming event reminders. Free-text rather than a check
  -- constraint's fixed list, since this is a display-only feed and new
  -- categories shouldn't require a migration.
  category      text not null,
  message       text not null,
  -- Hex color driving the icon's accent in the UI (e.g. "#2E6B4C" for a
  -- positive/verified event, "#B5432E" for a rejection) — kept here
  -- rather than derived client-side from category, since category
  -- strings are free-text and a lookup table would be overkill for a
  -- display feed.
  accent_color  text not null default '#1E1B16',
  -- Optional link back to the event/approval this entry describes, for
  -- entries generated by real actions (event_approved/event_rejected).
  -- Nullable — most seeded demo rows have no real backing row.
  event_id      uuid references public.events(id) on delete set null,
  actor_id      uuid references public.profiles(id) on delete set null,
  created_at    timestamptz not null default now()
);

create index idx_platform_activity_created_at on public.platform_activity (created_at desc);

comment on table public.platform_activity is
  'Display-only feed for the Admin Dashboard "Platform Activity" panel. Seeded with realistic demo rows; also appended to by approveEventApproval()/rejectEventApproval() in src/lib/approvals.ts.';

alter table public.platform_activity enable row level security;

-- Only admins see the feed — same audience as the dashboard it backs.
create policy "platform_activity_select_admin" on public.platform_activity
for select to authenticated
using (public.is_admin());

-- Only admins can write entries directly from the client. Real
-- approve/reject actions run as the calling admin anyway, so this covers
-- both the manual "seed more later" case and the app's own writes.
create policy "platform_activity_insert_admin" on public.platform_activity
for insert to authenticated
with check (public.is_admin());
